name: Deploy SilverStripe  Site

# Set these to your values
env:
  SSH_USERNAME: value
  SSH_HOST: X.X.X.X or example.com
  REMOTE_PATH: /container/application/

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.2.1
        with:
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ env.SSH_HOST }}
          port: 22
          script: |
            cd ${{ env.REMOTE_PATH }} &&
            git pull origin main && 
            composer install --no-dev --optimize-autoloader --no-interaction --no-progress &&
            php vendor/silverstripe/framework/cli-script.php dev/build flush=all
