name: Deploy SilverStripe Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        run: |
          # SSH into server, pull latest code, update dependencies, and build SilverStripe
          ssh $SERVER_USER@$SERVER_HOST "cd $PROJECT_PATH && \
            git pull && \
            composer install --no-dev --optimize-autoloader --no-interaction --no-progress && \
            php vendor/silverstripe/framework/cli-script.php dev/build flush=all"
